# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170722_1540'),
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='login.User'),
        ),
    ]
