# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='like',
            new_name='liked_by',
        ),
    ]
